# This is a basic workflow to help you get started with Actions

name: Deploy Nullkooland to GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - '!src/Nullkooland.Client/wwwroot/posts/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    # Use ubuntu-latest image to run this job
    runs-on: ubuntu-latest

    steps:
    # Checkout code from master branch
    - name: Checkout
      uses: actions/checkout@v2
      
    # Setup .NET SDK
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
 
    # Publish the project
    - name: Publish Blazor WASM
      run: dotnet publish src/Nullkooland.Client -c Release -o publish --nologo
      
    # Change the base url in index.html to repo name
#    - name: Change base url
#      run: sed -i 's/<base href="\/"/<base href="\/Nullkooland\/"/g' publish/wwwroot/index.html
      
    # Fix 404 page
    - name: Copy index.html to 404.html
      run: cp publish/wwwroot/index.html publish/wwwroot/404.html
      
    # Get lost jekyll, this is cool kids' party!
    - name: Add .nojekyll file
      run: touch publish/wwwroot/.nojekyll
      
    # Commit published wwwroot to GitHub Pages
    - name: Commit to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        # Deploy to gh-pages branch
        branch: gh-pages
        # Deploy everything in wwwroot
        folder: publish/wwwroot 
        # Automatically remove deleted files from the deploy branch
        clean: true 
        # Don't touch posts dir
        clean-exclude: |
          posts
