# This is a basic workflow to help you get started with Actions

name: Update blog posts

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the posts branch
  pull_request:
    branches:
      - posts
    paths-ignore:
      - '.gitignore'
      - '.github/**'
      - 'tools/avif_converter.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-blog-posts:
    # Use ubuntu-latest image to run this job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out posts branch
      - name: Checkout posts
        uses: actions/checkout@v2
        with: 
          ref: posts
          path: posts

      # Read metadata from posts and generate indexing json
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Python version range
          architecture: x64

      # Read metadata from posts and generate indexing json
      - name: Read metadata and generate index
        run: python3 posts/tools/gen_index.py --dir posts

      # Checks-out gh-pages branch
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with: 
          ref: gh-pages
          path: gh-pages

      # Copy the 'posts/' to 'gh-pages/'
      - name: Copy posts over
        run: rsync -av --recursive --delete --checksum --progress --exclude={'.gitignore','.github','tools'} posts/ gh-pages/posts/

      # Commit changes in gh-pages branch
      - name: Commit changes
        run: |
          cd gh-pages
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update posts"

      # Push gh-pages branch to GitHub repo
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: gh-pages
